# Site settings
title: YAWn!
email: bzz.products@gmail.com
description: >
  Kick(ed) nicklamer ass

baseurl: ""
url: https://yawnsite.github.io # the base hostname & protocol for your site
git_address: https://github.com/yawnsite

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"
- scope:
    path: _history
    type: history
  values:
    layout: page
    sectionid: page

collections:
  history:
    permalink: /:history/:path/
    output: true
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
